import { useEffect, useRef, useState } from 'react'
import { isMobileViewport, prefersReducedMotion } from '../lib/env'
import { loaderDone } from './Loader'
import { mulberry32 } from '../lib/random'

/**
 * Abhishek, as an 81-frame image sequence cut from a turntable video.
 * - Desktop: cursor X picks the frame, so he turns to look at the pointer.
 * - Mobile: phone tilt (or scroll, if tilt is unavailable).
 * - Idle: a gentle auto-sway.
 * His silhouette is traced by glowing graph edges drawn behind him,
 * so he sits inside the 3D node network.
 * Frames/contours are generated by design/video/export_seq.py.
 */

type Meta = { count: number; front: number; contours: [number, number][][] }

const BASE = '/img/hero-seq'
const W = 720
const H = 900
const EDGE_CUTOFF = 0.8 // below this y the matte fades out — no edges there
const IDLE_MS = 2200
const OUTSET = 7 // px (at 720w) the outline sits outside the silhouette

/** Load order that fills the range coarse-to-fine: front, ends, then midpoints. */
function loadOrder(count: number, front: number) {
  const seen = new Set<number>([front, 0, count - 1])
  const order = [front, 0, count - 1]
  for (let step = 32; step >= 1; step = Math.floor(step / 2)) {
    for (let i = 0; i < count; i += step) if (!seen.has(i)) (seen.add(i), order.push(i))
    if (step === 1) break
  }
  return order
}

export default function HeroFigure({ alt }: { alt: string }) {
  const root = useRef<HTMLDivElement>(null)
  const frameCanvas = useRef<HTMLCanvasElement>(null)
  const edgeCanvas = useRef<HTMLCanvasElement>(null)
  const [ready, setReady] = useState(false)
  const [mobile] = useState(isMobileViewport)
  const set = mobile ? 'm' : 'd'
  const poster = `${BASE}/${set}/048.webp`

  useEffect(() => {
    if (prefersReducedMotion()) return
    const el = root.current!
    const fc = frameCanvas.current!
    const ec = edgeCanvas.current!
    const fctx = fc.getContext('2d')!
    const ectx = ec.getContext('2d')!
    let meta: Meta | null = null
    const images: (HTMLImageElement | null)[] = []
    let raf = 0
    let visible = true
    let alive = true

    // ── sizing ────────────────────────────────────────────
    const resize = () => {
      const r = el.getBoundingClientRect()
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      for (const c of [fc, ec]) {
        c.width = Math.round(r.width * dpr)
        c.height = Math.round(r.height * dpr)
      }
    }
    const ro = new ResizeObserver(resize)
    ro.observe(el)

    // ── input → target frame (as -1..1, 0 = facing camera) ──
    let rel = 0
    let lastInput = -Infinity
    let tiltActive = false
    const onPointer = (e: PointerEvent) => {
      if (e.pointerType !== 'mouse') return
      const r = el.getBoundingClientRect()
      const cx = r.left + r.width / 2
      // Normalise by the distance to the far screen edge so both extremes are reachable.
      const span = e.clientX < cx ? cx : window.innerWidth - cx
      rel = Math.max(-1, Math.min(1, (e.clientX - cx) / Math.max(1, span)))
      lastInput = performance.now()
    }
    const onTilt = (e: DeviceOrientationEvent) => {
      if (e.gamma == null) return
      tiltActive = true
      rel = Math.max(-1, Math.min(1, e.gamma / 25))
      lastInput = performance.now()
    }
    const onScroll = () => {
      if (!mobile || tiltActive) return
      const p = Math.min(1, window.scrollY / (el.getBoundingClientRect().height || 1))
      rel = p * 1.4 - 0.2 // turns as the hero scrolls away
      lastInput = performance.now()
    }
    // iOS needs permission from a user gesture before it sends orientation.
    const askTilt = () => {
      const DOE = window.DeviceOrientationEvent as unknown as { requestPermission?: () => Promise<string> }
      if (DOE?.requestPermission) DOE.requestPermission().catch(() => {})
    }
    window.addEventListener('pointermove', onPointer, { passive: true })
    if (mobile) {
      window.addEventListener('deviceorientation', onTilt)
      window.addEventListener('scroll', onScroll, { passive: true })
      window.addEventListener('touchend', askTilt, { once: true })
    }

    const io = new IntersectionObserver(([e]) => {
      visible = e.isIntersecting
      if (visible && !raf) raf = requestAnimationFrame(loop)
    })
    io.observe(el)

    // ── decorative network nodes orbiting the silhouette ──
    const rand = mulberry32(11)
    const halo = Array.from({ length: 16 }, (_, i) => {
      const side = i % 2 ? 1 : -1
      return { x: 0.5 + side * (0.36 + rand() * 0.14), y: 0.06 + rand() * 0.66, r: 1 + rand() * 1.6, phase: rand() * 6.28 }
    })

    // ── render loop ───────────────────────────────────────
    let current = -1
    let reveal = 0
    const t0 = performance.now()

    const nearestLoaded = (i: number) => {
      for (let d = 0; d < images.length; d++) {
        if (images[i - d]) return images[i - d]
        if (images[i + d]) return images[i + d]
      }
      return null
    }

    function loop(now: number) {
      raf = 0
      if (!alive || !visible || !meta) return
      const t = (now - t0) / 1000
      const n = meta.count - 1
      const front = meta.front
      const idle = now - lastInput > IDLE_MS
      // Idle: slow, layered sway around the front-facing frame.
      const sway = Math.sin(t * 0.42) * 0.32 + Math.sin(t * 0.17 + 1) * 0.12
      const r = idle ? sway : rel
      const target = r < 0 ? front + r * front : front + r * (n - front)
      if (current < 0) current = front
      current += (target - current) * (idle ? 0.04 : 0.14)
      const i = Math.round(current)

      // frame
      const img = images[i] ?? nearestLoaded(i)
      if (img) {
        fctx.clearRect(0, 0, fc.width, fc.height)
        fctx.drawImage(img, 0, 0, fc.width, fc.height)
      }

      // silhouette edges (interpolated between neighbouring contours)
      reveal = Math.min(1, reveal + 0.012)
      const lo = Math.floor(current)
      const hi = Math.min(n, lo + 1)
      const f = current - lo
      const A = meta.contours[lo]
      const B = meta.contours[hi]
      const sx = ec.width
      const sy = ec.height
      const scale = sx / W
      const raw = A.map(([ax, ay], k) => [(ax + (B[k][0] - ax) * f) * sx, (ay + (B[k][1] - ay) * f) * sy, ay + (B[k][1] - ay) * f] as const)
      // Push each point outward along its normal so the outline sits just outside
      // the body as a rim — otherwise the figure (drawn on top) hides it.
      const len = raw.length
      const pts = raw.map((p, k) => {
        const a = raw[(k - 1 + len) % len]
        const b = raw[(k + 1) % len]
        let nx = b[1] - a[1]
        let ny = -(b[0] - a[0])
        const m = Math.hypot(nx, ny) || 1
        nx /= m
        ny /= m
        // Contour winding decides which side is "out"; test against the figure centre.
        if ((p[0] - sx / 2) * nx + (p[1] - sy * 0.45) * ny < 0) (nx = -nx), (ny = -ny)
        const push = OUTSET * scale
        return [p[0] + nx * push, p[1] + ny * push, p[2]] as const
      })
      const visibleCount = Math.floor(pts.length * reveal)

      ectx.clearRect(0, 0, sx, sy)
      ectx.globalCompositeOperation = 'lighter'
      ectx.lineCap = 'round'

      // edges
      for (let k = 0; k < visibleCount; k++) {
        const p = pts[k]
        const q = pts[(k + 1) % pts.length]
        if (p[2] > EDGE_CUTOFF && q[2] > EDGE_CUTOFF) continue
        const fade = Math.max(0, 1 - Math.max(0, Math.max(p[2], q[2]) - 0.6) / (EDGE_CUTOFF - 0.6))
        ectx.strokeStyle = `rgba(130,175,255,${0.95 * fade})`
        ectx.shadowColor = 'rgba(79,140,255,1)'
        ectx.shadowBlur = 18 * scale
        ectx.lineWidth = 1.8 * scale
        ectx.beginPath()
        ectx.moveTo(p[0], p[1])
        ectx.lineTo(q[0], q[1])
        ectx.stroke()
      }
      ectx.shadowBlur = 0

      // spokes from the silhouette out to halo nodes
      for (const h of halo) {
        const hx = h.x * sx
        const hy = h.y * sy
        let best = 0
        let bd = Infinity
        for (let k = 0; k < visibleCount; k++) {
          const d = (pts[k][0] - hx) ** 2 + (pts[k][1] - hy) ** 2
          if (d < bd && pts[k][2] < EDGE_CUTOFF) (bd = d), (best = k)
        }
        if (bd === Infinity) continue
        const tw = 0.5 + 0.5 * Math.sin(t * 1.3 + h.phase)
        ectx.strokeStyle = `rgba(150,110,255,${0.38 * reveal})`
        ectx.lineWidth = 1 * scale
        ectx.beginPath()
        ectx.moveTo(pts[best][0], pts[best][1])
        ectx.lineTo(hx, hy)
        ectx.stroke()
        ectx.fillStyle = `rgba(190,170,255,${(0.35 + tw * 0.5) * reveal})`
        ectx.beginPath()
        ectx.arc(hx, hy, h.r * scale * 1.6, 0, Math.PI * 2)
        ectx.fill()
      }

      // nodes on the silhouette
      for (let k = 0; k < visibleCount; k += 2) {
        const p = pts[k]
        if (p[2] > EDGE_CUTOFF - 0.04) continue
        ectx.fillStyle = 'rgba(225,235,255,1)'
        ectx.beginPath()
        ectx.arc(p[0], p[1], 2.6 * scale, 0, Math.PI * 2)
        ectx.fill()
      }

      // data pulses travelling around the outline
      if (reveal >= 1) {
        for (let j = 0; j < 3; j++) {
          const pos = ((t * 0.07 + j / 3) % 1) * pts.length
          const k = Math.floor(pos)
          const p = pts[k]
          const q = pts[(k + 1) % pts.length]
          if (p[2] > EDGE_CUTOFF) continue
          const u = pos - k
          const x = p[0] + (q[0] - p[0]) * u
          const y = p[1] + (q[1] - p[1]) * u
          const g = ectx.createRadialGradient(x, y, 0, x, y, 14 * scale)
          g.addColorStop(0, 'rgba(255,255,255,0.95)')
          g.addColorStop(0.3, 'rgba(120,170,255,0.6)')
          g.addColorStop(1, 'rgba(79,140,255,0)')
          ectx.fillStyle = g
          ectx.beginPath()
          ectx.arc(x, y, 14 * scale, 0, Math.PI * 2)
          ectx.fill()
        }
      }
      ectx.globalCompositeOperation = 'source-over'

      raf = requestAnimationFrame(loop)
    }

    // ── loading ───────────────────────────────────────────
    const start = async () => {
      const res = await fetch(`${BASE}/meta.json`)
      meta = (await res.json()) as Meta
      if (!alive) return
      images.length = meta.count
      images.fill(null)
      const order = loadOrder(meta.count, meta.front)
      const loadOne = (i: number) =>
        new Promise<void>((done) => {
          const im = new Image()
          im.decoding = 'async'
          im.src = `${BASE}/${set}/${String(i).padStart(3, '0')}.webp`
          im.decode().then(
            () => ((images[i] = im), done()),
            () => done(),
          )
        })
      await loadOne(order[0])
      if (!alive) return
      resize()
      setReady(true)
      raf = requestAnimationFrame(loop)
      // Remaining frames, a few at a time, coarse-to-fine.
      for (let k = 1; k < order.length && alive; k += 6) await Promise.all(order.slice(k, k + 6).map(loadOne))
    }
    loaderDone.then(() => {
      const idle = (window as Window & { requestIdleCallback?: (cb: () => void) => number }).requestIdleCallback
      idle ? idle(() => void start()) : setTimeout(() => void start(), 200)
    })

    return () => {
      alive = false
      cancelAnimationFrame(raf)
      ro.disconnect()
      io.disconnect()
      window.removeEventListener('pointermove', onPointer)
      window.removeEventListener('deviceorientation', onTilt)
      window.removeEventListener('scroll', onScroll)
      window.removeEventListener('touchend', askTilt)
    }
  }, [mobile, set])

  return (
    <div ref={root} className={`hero-figure${ready ? ' is-live' : ''}`}>
      <canvas ref={edgeCanvas} className="hf-edges" aria-hidden="true" />
      <img className="hf-poster" src={poster} alt={alt} width={W} height={H} fetchPriority="high" decoding="async" />
      <canvas ref={frameCanvas} className="hf-frames" aria-hidden="true" />
    </div>
  )
}
